package_index.json

This library makes it easy to monitor files for change.
Simply tag a variable that contains the path to the file you want to monitor
with `FIM=all_changes`.
For example:
```
vars:
"fstab" string => "/etc/fstab", meta => { "FIM=all_changes" };
```

Added lib-FIM to the package index

---

test/test_pretty.py

Fixed a bug in test `test_pretty` where a non-ordered dict is passed to
an ordered dict. This could cause the dict to be iterated over in the
wrong order in older versions of python, causing the test to fail.
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

Fixed bug in test `test_pretty`

---

cfbs/utils.py

CFE-3757: Make invalid json error easier to read

---

cfbs/commands.py
cfbs/main.py
cfbs/validate.py

Ticket: None
Changelog: Title
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

Implemented command `validate`

---

cfbs/commands.py

If local module doesn't exist, give a nice error
If module doesn't have a commit property, give a nice error
Ticket: none

Improve missing module errors during build command

---

cfbs/commands.py

So that we have download statistics.

Use archive.build.cfengine.com instead of S3 when downloading modules

---

cfbs/commands.py

Before:
```
002 autorun     : json 'defz.json' 'masterfiles/def.json'
Traceback (most recent call last):
File "/home/olehermanse/.local/bin/cfbs", line 8, in <module>
sys.exit(main())
File "/home/olehermanse/.local/lib/python3.8/site-packages/cfbs/main.py", line 145, in main
return commands.build_command()
File "/home/olehermanse/.local/lib/python3.8/site-packages/cfbs/commands.py", line 949, in build_command
build_steps()
File "/home/olehermanse/.local/lib/python3.8/site-packages/cfbs/commands.py", line 931, in build_steps
build_step(module, step, module_name_length)
File "/home/olehermanse/.local/lib/python3.8/site-packages/cfbs/commands.py", line 872, in build_step
assert extras is not None
AssertionError
$
```
After:
```
002 autorun     : json 'defz.json' 'masterfiles/def.json'
Error: …
```

Added a better error message during build when a json file is misspelled

---

cfbs/commands.py

```
$ cfbs remove https://github.com/cfengine/modules/archive/refs/heads/master.zip
Do you wish to remove 'autorun'? [y/N] y
Removing module 'autorun'
Do you wish to remove 'client-initiated-reporting'? [y/N] y
Removing module 'client-initiated-reporting'
Do you wish to remove 'every-minute'? [y/N] N
[...]
```
Ticket: CFE-3844

Made it possible to remove modules added by URL

---

cfbs/commands.py
test/shell/010_local_add.sh
test/shell/all.sh

Format matches that of cfbs build;
```
$ cfbs status
Name:        Example
Description: Example description
File:        cfbs.json
Modules:
001 masterfiles @ 5c7dc5b43088e259a94de4e5a9f17c0ce9781a0f (Downloaded)
002 autorun     @ c3b7329b240cf7ad062a0a64ee8b607af2cb912a (Downloaded)
003 ./test.cf   @ local                                    (Copied)
```

Fixed status command for locally added policy files

---

cfbs/commands.py
cfbs/main.py
cfbs/pretty.py
test/test_pretty.py

https://github.com/cfengine/build-index/blob/master/CONTRIBUTING.md#publishing-your-module-for-others-to-reuse
defines ordering for the modules attributes so `cfbs pretty`
should make sure they are in order.
Ticket: CFE-3834
Changelog: 'cfbs pretty' now sorts modules and their attributes

Sort modules and their attributes as desired in 'cfbs pretty'

---

cfbs/main.py

The new format is more human friendly and clean.
Before:
```
WARNING:root:No bundles tagged with autorun found in: './dir/'
```
After:
```
WARNING: No bundles tagged with autorun found in: './dir/'
```

Removed root: logger name in log messages

---

README.md
cfbs/commands.py

When working with cf-remote spawned / saved hosts, and a cfbs
project cf-remote will have easy defaults in the next release,
so we should show this.

Updated README and command suggestions for cf-remote deploy

---

cfbs/utils.py

So that we can distinguish CI downloads from real downloads.
Ticket: ENT-7919
Changelog: CFBS_USER_AGENT environment variable can now be used to set User-Agent for file downloads

Support specifying User-Agent for downloads in an env var

---

cfbs/commands.py
cfbs/git_magic.py
cfbs/main.py
test/shell/011_update.sh

cfbs update now supports specifying module name (or name and version) by
using the following format `cfbs update [NAME[@VERSION]]...`.
Ticket: ENT-8573 and ENT-8579
Changelog: Body
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

ENT-8573 & ENT-8579: cfbs update now supports specifying modules

---

cfbs/commands.py

Single module update output:
```
$ cfbs update
Updated module 'promise-type-groups' from version 0.1.2 to version 0.1.3
The default commit message is 'Updated module 'promise-type-groups' from version 0.1.2 to version 0.1.3' - edit it? [yes/y/NO/n] 
Committing using git:
[master b0e2c32] Updated module 'promise-type-groups' from version 0.1.2 to version 0.1.3
1 file changed, 2 insertions(+), 2 deletions(-)
```
Multi module update output:
```
$ cfbs update
Updated 2 modules
- Updated module 'promise-type-groups' from version 0.1.2 to version 0.1.3
- Updated module 'promise-type-git' from version 0.1.0 to version 0.1.1
The default commit message is:
Updated 2 modules
- Updated module 'promise-type-groups' from version 0.1.2 to version 0.1.3
- Updated module 'promise-type-git' from version …
```

CFE-3860: cfbs now prints what modules were updated

---

cfbs/args.py
cfbs/commands.py
cfbs/main.py

Allows use of custom index or testing changes to default index
by ignoring versions.json.
Ticket: ENT-7914
Changelog: title

ENT-7914: Added --ignore-versions-json argument for build command

---

cfbs/build.py
cfbs/cfbs_config.py
cfbs/index.py
cfbs/prompts.py
cfbs/utils.py
tests/shell/010_local_add.sh
tests/shell/016_add_folders.sh
tests/test_utils.py

**Demo:**
```
$ tree .
.
├── bogus.cf
├── cfbs.json
└── doofus
├── doofus.cf
└── foo
└── foo.cf
2 directories, 4 files
$ cfbs add ./bogus.cf 
Which bundle should be evaluated (added to bundle sequence)?
1. ./bogus.cf:bogus (default)
2. (None)
[1/2]: 1
Added module: ./bogus.cf
$ cfbs add ./doofus/
Which bundle should be evaluated (added to bundle sequence)?
1. ./doofus/doofus.cf:doofus (default)
2. ./doofus/foo/foo.cf:foobar
3. ./doofus/foo/foo.cf:foobaz
4. (None)
[1/2/3/4]: 2
Added module: ./doofus/
$ cfbs build
--snip--
002 ./bogus.cf  : copy './bogus.cf' 'masterfiles/services/cfbs/bogus.cf'
002 ./bogus.cf  : policy_files 'services/cfbs/bogus.cf'
002 ./bogus.cf  : bundles 'bogus'
003 ./doofus/   : directory './' 'masterfiles/services/cfbs/doofus/'
003 ./doofus/   : policy_files …
```

CFE-3990: Prompt user which bundle to run

---

cfbs/commands.py
tests/shell/031_get_set_input_pipe.sh
tests/shell/032_set_input_unordered.sh
tests/shell/all.sh

More work remains to fix committing in `cfbs add`.

CFE-4081: Fixed commiting of changes made by set-input

---

README.md
cfbs/args.py
cfbs/commands.py
cfbs/main.py
cfbs/utils.py
tests/shell/031_get_set_input_pipe.sh
tests/shell/032_set_input_unordered.sh
tests/shell/033_add_commits_local_files.sh
tests/shell/common.sh

The help menu was looking for functions ending with _command
and taking the first word of those functions. This no longer works
correctly, some commands are multiple words and some of those
functions are not commands.

Fixed list of commands in help and added README documentation on commands and interactivity

---

.github/workflows/black-format.yml
.github/workflows/black.yml
.github/workflows/python-publish.yml
.github/workflows/python-tests.yml
.github/workflows/python-validate-test.yml

ubuntu-latest gives you the russian roulette feature of sometimes picking 22 and sometimes 20. If you get 22, python 3.6 and 3.5 will fail.

Changed from ubuntu-latest to ubuntu 20

---

cfbs/utils.py

We don't want to use sh() for cfbs commands which
are used in the Mission Portal Build application.
Ticket: ENT-9710

ENT-9710: Switched to pythonic mkdir -p

---

cfbs/build.py
cfbs/commands.py
cfbs/utils.py

- Changed delete step behavior to allow for non-existent paths
- Changed init --masterfiles implementation to add with commit instead of modify index version of masterfiles module

CFE-4527: Change delete step and init --masterfiles behavior

---

cfbs/cfbs_config.py
cfbs/prompts.py

Changed hardcoded print of [y/N] to [yes/y/NO/n] using helper function to be consistent
Ticket: ENT-8980

 ENT-8980: The prompt for adding all modules now has yes/y/no/n options, like the other prompts

---

setup.py

The current build installs the tests files into site-packages in the `tests` folder, which is probably not what we want.

Removed tests from the installed python package

---

cfbs/build.py
cfbs/commands.py
tests/shell/026_init_no_masterfiles.sh

Added many helpful error messages to tell the user what
is wrong with their cfbs.json (why they cannot run cfbs
build or cfbs download).
The config must have a build field, with a list of modules,
each module must have a name, a non-empty list of steps,
each step must be a non-empty string, etc.
Ticket: ENT-10944

ENT-10944: cfbs build/download: Added validation and error messages

---

cfbs/cfbs_config.py
cfbs/cfbs_json.py

"build" key is only required for the "policy-set" type.
However, we still want users to be able to use the "build"
key and "cfbs build" in all projects, so we need to add the
key for them when necessary, and account for the fact that
the key might be missing.

Fixed issues when adding modules to missing build key

---

cfbs/cfbs_config.py
cfbs/commands.py
cfbs/pretty.py
cfbs/validate.py

- De-duplicated cfbs sorting rules
- Renamed sorting rule variables
- Fixed pretty formatting of first cfbs init commit
- Updated imports for top level keys and module keys

Fixed pretty formatting of first cfbs init commit

---

cfbs/validate.py

We wanted to make a `rhel_7_stig` namespace, which seems reasonable
so let's allow it.
I've seen other langauges not allowing identifiers to start with a number
to make things less ambiguous, so let's do that.
For example, `rhel_7_stig` is considered an acceptable namespace, while
`123`, `100_000`, and `1M` are not, since they look like values / numbers.

Allowed numbers in namespaces in module input

---

cfbs/git.py
cfbs/git_magic.py

CFE-3967: cfbs should not try to commit without diff

---

cfbs/commands.py

This was an accidental print statement left in by me when I
was fixing the sorting of this JSON file (specifically the
git field).

Stopped printing cfbs.json content as part of cfbs init

---

cfbs/pretty.py
tests/test_pretty.py

CFE-3785: Changed cfbs pretty command to always wrap non-empty top level collections

---

cfbs/git.py

ENT-11811: cfbs recognizes and commits module input changes

---

cfbs/args.py
cfbs/cfbs.1
cfbs/commands.py
cfbs/main.py
cfbs/man_generator.py
setup.py

added -M option to show generated man page

---

cfbs/build.py
cfbs/cfbs_config.py
cfbs/commands.py

Before:
```
$ cfbs status
Name:        Example project
Description: Example description
File:        cfbs.json
Modules:
001 masterfiles               @ 691c6b2d11eefcfcda2e2b0d1de33440cec112a9 (Downloaded)
002 autorun                   @ c3b7329b240cf7ad062a0a64ee8b607af2cb912a (Not downloaded)
003 ./policy-module-template/ @ local                                    (Copied)
```
After:
```
$ cfbs status
Name:        Example project
Description: Example description
File:        cfbs.json
Modules:
001 masterfiles               @ 3.21.5 / 691c6b2d11eefcfcda2e2b0d1de33440cec112a9 (Downloaded)
002 autorun                   @ 1.0.1  / c3b7329b240cf7ad062a0a64ee8b607af2cb912a (Not downloaded)
003 ./policy-module-template/ @ local                                             (Copied)
```

ENT-9556: `cfbs status` now displays module versions in addition to commit hashes

---

cfbs/commands.py
cfbs/git.py

Changelog: Title
Ticket: ENT-11437

ENT-11437: `cfbs init` no longer displays a traceback when `git` is not found

---

.github/actions/set-up-legacy-python/action.yml
.github/workflows/black-format.yml
.github/workflows/black.yml
.github/workflows/python-publish.yml
.github/workflows/python-tests.yml
.github/workflows/python-validate-test.yml

Ubuntu 20.04 runner is being deprecated.

Bump runner Ubuntu version, while handling legacy Python versions

---

cfbs/commands.py

- **commands.py: Added some more return type hints**
- **commands.py: Fixed return value of build_command**

Fixed return value of build_command and added more type hints

---

cfbs/build.py
cfbs/commands.py

- **Renamed perform_build_steps to perform_build**
- **'cfbs build' now includes cfbs.json into the policy set**

'cfbs build' now includes cfbs.json into the policy set

---

.github/workflows/add_validate_build_all.sh
.github/workflows/add_validate_build_all.yaml
cfbs/cfbs_json.py
cfbs/validate.py
tests/shell/011_update.sh
tests/test_validate_mock_index.py
tests/test_validate_mock_input.py

More fixes are needed to fix the actual issue (not just the log spamming), but this is a good improvement.

Fixed issues with repeated validation errors / warnings

---

.github/workflows/update-cfbs-manual.yml

For some reason, the automatic commit seems to add a co-author and thus fails the GPG verification; also, this improves the commit message.

Explicitly make a Git commit in the man page generator workflow

---

.github/workflows/python-tests.yml

The legacy Python tests did not actually fail on flake8 errors like the regular tests, as 47b29d18e9d926954beabb265e54354f65586454 was applied only to the regular tests flake8 call

Use the same flake8 command in legacy Python tests as in regular tests

---

.github/actions/set-up-legacy-python/action.yml
.github/workflows/python-tests.yml

[The test failure](https://github.com/cfengine/cfbs/actions/runs/17440296379/job/49521243897).

Fix Python 3.5 test failures related to Pyright
