cfengine/cfbs

cfbs/pretty.py
test/test_pretty.py

Signed-off-by: larsewi <lars.erik.wik@northern.tech>

Added function `pretty` for pretty printing JSON

---

cfbs/commands.py
cfbs/main.py
test/sample/bar/baz/main.cf
test/sample/bar/my.json
test/sample/cfbs.json
test/sample/foo/main.cf
test/test_showinfo.py

Ticket: CFE-3764
Changelog: title

CFE-3764 Added show/info command

---

cfbs/commands.py
cfbs/index.py
cfbs/utils.py

The logic for interacting with cfbs.json and the index is
repetitive and confusing.
I am trying to organize things better and will introduce
additional commits in this direction.

Added a new class for the CFBS config

---

cfbs/index.py
test/test_showinfo.py

Fixed cfbs search where no cfbs.json present

---

README.md
cfbs/commands.py
cfbs/main.py

Added command `cfbs remove` which can be used to remove added modules.
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

CFE-3767: Added command `cfbs remove`

---

cfbs/commands.py

If an argument is provided, install will use that path
If no argument and root is the user, default path of /var/cfengine/masterfiles is used
If no argument and NOT root user, $HOME/.cfagent/inputs is used
Ticket: CFE-3821

CFE-3821 Modified cfbs install behavior for easier use

---

cfbs/commands.py
cfbs/index.py

CFE-3829 Added error messages for missing required keys in module definition

---

cfbs/index.py

CFE-3830 Added error message in case of build property missing from cfbs.json

---

README.md

CFE-3835 Added information about build step types to README

---

cfbs/commands.py
cfbs/pretty.py

Fixed error causing cfbs pretty to clear contents of invalid JSON files

---

cfbs/commands.py
cfbs/index.py

Ticket: [CFE-3871](https://tracker.mender.io/browse/CFE-3871)

Fixed crash (Traceback) when adding modules

---

cfbs/commands.py
cfbs/core.py
test/shell/011_update.sh

See: https://github.com/cfengine/cfbs/pull/88

Follow-up fixes after PR #88

---

cfbs/core.py
cfbs/internal_file_management.py
test/shell/013_add_url_commit.sh
test/shell/all.sh

- Fixed bug with adding URL at specific commit
- Added test for adding a URL at specific commit
- Fixed problems with adding/cloning the same URL and commit twice

Fixed bugs with adding URL at specific commit

---

README.md
setup.py

pip no longer accepted the version numbers straight from git,
so I had to convert it.

Fixed local install version numbers

---

cfbs/prompts.py

Same as if user just hit ENTER -- use the default.
Ticket: ENT-8488

Handle EOF in prompts

---

cfbs/commands.py

Ticket: CFE-3970
Changelog: none

CFE-3970: Add error message when info/show has no arguments

---

cfbs/validate.py

Ticket: CFE-3905
Changelog: none

CFE-3905: Revert extra print statement in validate command

---

README.md
cfbs/cfbs_config.py
cfbs/commands.py
cfbs/index.py
cfbs/internal_file_management.py
cfbs/main.py
test/shell/016_add_folders.sh

- Fixed inconsistency when handling local folders as modules
- README.md: Added some more explanation about build steps
- Ensured cfbs init respects --non-interactive

Fixed inconsistency when handling local folders as modules

---

cfbs/validate.py

Ticket: ENT-9025
Changelog: title

ENT-9025: Fixed tags attribute validation coding error

---

cfbs/cfbs_config.py
cfbs/index.py

Ticket: ENT-9024
Changelog: title

ENT-9024: Add custom indexes to each module config as they are added

---

cfbs/cfbs_config.py

Follow ups on https://github.com/cfengine/cfbs/pull/133#pullrequestreview-1152785904

Follow ups on PR review

---

cfbs/main.py
tests/shell/028_init_masterfiles_version_3.18.2.sh
tests/shell/029_init_masterfiles_version_3.18.1-1.sh

Follow-ups from https://github.com/cfengine/cfbs/pull/135

CFE-4071: Follow ups

---

tests/shell/all.sh

Do not include downloads made by tests into the build modules statistics

---

.github/workflows/python-tests.yml
.github/workflows/python-validate-test.yml
cfbs/commands.py

CFE-3819: cfbs remove - prompt user before removing module dependency

---

README.md

cfbs works with CFEngine modules not packages.

Replace packages with modules in README.md

---

cfbs/masterfiles/analyze.py
cfbs/masterfiles/check_download_matches_git.py

ENT-12486: Improve the release-information JSON file format

---

cfbs/cfbs.1
cfbs/man_generator.py

- **Re-generated man page file**
- **Improved error message for missing dependency**

Re-generated man page ahead of next release
